# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "souq-app-chart.fullname" . }}
  labels:
    app: souq-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: souq-app
  template:
    metadata:
      labels:
        app: souq-app
    spec:
      containers:
        - name: souq-app-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
